//! SCXML-to-Rust code generation.
//!
//! Reads a parsed [`ScxmlDocument`] and generates Rust source code:
//! - State enum (one variant per state)
//! - Event enum (one variant per unique event)
//! - Transition table function
//! - Handler trait (one method per state with `<onentry>`)
//! - `StatechartSpec` implementation

use crate::parser::ScxmlDocument;
use crate::types::*;

/// Generate Rust source code from a parsed SCXML document.
pub fn generate_rust(doc: &ScxmlDocument) -> String {
    generate_rust_with_spec_path(doc, "nivasa_statechart")
}

/// Generate Rust source code from a parsed SCXML document with a custom
/// `StatechartSpec` path. This lets the same generator compile both inside
/// the `nivasa_statechart` crate and in downstream crates that depend on it.
pub fn generate_rust_with_spec_path(doc: &ScxmlDocument, spec_path: &str) -> String {
    let chart_name = doc
        .metadata
        .name
        .as_deref()
        .unwrap_or("Unnamed")
        .to_pascal_case();

    let hash = doc.content_hash();
    let states = collect_states(doc);
    let events = doc.event_names();
    let initial_state = doc
        .metadata
        .initial
        .as_deref()
        .or_else(|| doc.top_level_states.first().map(|s| s.as_str()))
        .unwrap_or("unknown");

    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "// AUTO-GENERATED by nivasa-statechart codegen\n\
         // DO NOT EDIT — modify the .scxml file instead.\n\
         // SCXML hash: sha256:{}\n\n",
        hash
    ));

    // State enum
    out.push_str(&generate_state_enum(&chart_name, &states));
    out.push('\n');

    // Event enum
    out.push_str(&generate_event_enum(&chart_name, &events));
    out.push('\n');

    // Transition table
    out.push_str(&generate_transition_fn(&chart_name, doc, &states, &events));
    out.push('\n');

    // valid_events_for
    out.push_str(&generate_valid_events_fn(&chart_name, doc, &states, &events));
    out.push('\n');

    // is_final
    out.push_str(&generate_is_final_fn(&chart_name, &states, doc));
    out.push('\n');

    // Handler trait
    let entry_states: Vec<String> = states
        .iter()
        .filter(|s| {
            doc.states
                .get(s.as_str())
                .map(|state| state.has_on_entry)
                .unwrap_or(false)
        })
        .cloned()
        .collect();
    out.push_str(&generate_handler_trait(&chart_name, &entry_states));
    out.push('\n');

    // StatechartSpec impl
    out.push_str(&generate_spec_impl(&chart_name, &hash, initial_state, spec_path));

    out
}

fn collect_states(doc: &ScxmlDocument) -> Vec<String> {
    let mut states: Vec<String> = doc.states.keys().cloned().collect();
    states.sort();
    states
}

fn generate_state_enum(chart_name: &str, states: &[String]) -> String {
    let mut out = format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n\
         pub enum {}State {{\n",
        chart_name
    );
    for state in states {
        out.push_str(&format!("    {},\n", state.to_pascal_case()));
    }
    out.push_str("}\n");
    out
}

fn generate_event_enum(chart_name: &str, events: &[String]) -> String {
    let mut out = format!(
        "#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n\
         pub enum {}Event {{\n",
        chart_name
    );
    for event in events {
        out.push_str(&format!("    {},\n", event.to_pascal_case()));
    }
    // Add a catch-all for error events
    out.push_str("}\n");
    out
}

fn generate_transition_fn(
    chart_name: &str,
    doc: &ScxmlDocument,
    _states: &[String],
    _events: &[String],
) -> String {
    let state_type = format!("{}State", chart_name);
    let event_type = format!("{}Event", chart_name);

    let mut out = format!(
        "pub fn {}_transition(current: &{}, event: &{}) -> Option<{}> {{\n\
             match (current, event) {{\n",
        chart_name.to_snake_case(),
        state_type,
        event_type,
        state_type
    );

    for state_id in collect_states(doc) {
        let state = doc.states.get(&state_id).expect("state id must exist");
        for transition in &state.transitions {
            if let Some(ref event) = transition.event {
                if let Some(target) = transition.target.first() {
                    out.push_str(&format!(
                        "        ({}::{}, {}::{}) => Some({}::{}),\n",
                        state_type,
                        state.id.to_pascal_case(),
                        event_type,
                        event.to_pascal_case(),
                        state_type,
                        target.to_pascal_case(),
                    ));
                }
            }
        }
    }

    out.push_str("        _ => None,\n");
    out.push_str("    }\n}\n");
    out
}

fn generate_valid_events_fn(
    chart_name: &str,
    doc: &ScxmlDocument,
    _states: &[String],
    _events: &[String],
) -> String {
    let state_type = format!("{}State", chart_name);
    let event_type = format!("{}Event", chart_name);

    let mut out = format!(
        "pub fn {}_valid_events(state: &{}) -> Vec<{}> {{\n\
             match state {{\n",
        chart_name.to_snake_case(),
        state_type,
        event_type
    );

    for state_id in collect_states(doc) {
        let state = doc.states.get(&state_id).expect("state id must exist");
        let events: Vec<String> = state
            .transitions
            .iter()
            .filter_map(|t| t.event.as_ref())
            .map(|e| format!("{}::{}", event_type, e.to_pascal_case()))
            .collect();

        if events.is_empty() {
            out.push_str(&format!(
                "        {}::{} => vec![],\n",
                state_type,
                state.id.to_pascal_case()
            ));
        } else {
            out.push_str(&format!(
                "        {}::{} => vec![{}],\n",
                state_type,
                state.id.to_pascal_case(),
                events.join(", ")
            ));
        }
    }

    out.push_str("    }\n}\n");
    out
}

fn generate_is_final_fn(chart_name: &str, states: &[String], doc: &ScxmlDocument) -> String {
    let state_type = format!("{}State", chart_name);
    let final_states: Vec<_> = states
        .iter()
        .filter(|s| {
            doc.states
                .get(*s)
                .map(|st| st.state_type == StateType::Final)
                .unwrap_or(false)
        })
        .collect();

    let mut out = format!(
        "pub fn {}_is_final(state: &{}) -> bool {{\n\
             matches!(state, ",
        chart_name.to_snake_case(),
        state_type
    );

    if final_states.is_empty() {
        out.push_str("_ if false => true");
    } else {
        let patterns: Vec<String> = final_states
            .iter()
            .map(|s| format!("{}::{}", state_type, s.to_pascal_case()))
            .collect();
        out.push_str(&patterns.join(" | "));
    }

    out.push_str(")\n}\n");
    out
}

fn generate_handler_trait(chart_name: &str, entry_states: &[String]) -> String {
    let mut out = format!(
        "#[async_trait::async_trait]\n\
         pub trait {}Handler: Send + Sync {{\n",
        chart_name
    );

    for state_id in entry_states {
        out.push_str(&format!(
            "    async fn on_enter_{}(&self, ctx: &mut dyn std::any::Any) -> {}Event;\n",
            state_id.to_snake_case(),
            chart_name
        ));
    }

    out.push_str("}\n");
    out
}

fn generate_spec_impl(chart_name: &str, hash: &str, _initial: &str, spec_path: &str) -> String {
    let state_type = format!("{}State", chart_name);
    let event_type = format!("{}Event", chart_name);

    format!(
        "pub struct {}Statechart;\n\n\
         impl {}::StatechartSpec for {}Statechart {{\n\
             type State = {};\n\
             type Event = {};\n\n\
             fn transition(current: &Self::State, event: &Self::Event) -> Option<Self::State> {{\n\
                 {}_transition(current, event)\n\
             }}\n\n\
             fn valid_events_for(state: &Self::State) -> Vec<Self::Event> {{\n\
                 {}_valid_events(state)\n\
             }}\n\n\
             fn is_final(state: &Self::State) -> bool {{\n\
                 {}_is_final(state)\n\
             }}\n\n\
             fn name() -> &'static str {{\n\
                 \"{}\"\n\
             }}\n\n\
             fn scxml_hash() -> &'static str {{\n\
                 \"{}\"\n\
             }}\n\
         }}\n",
        chart_name,
        spec_path,
        chart_name,
        state_type,
        event_type,
        chart_name.to_snake_case(),
        chart_name.to_snake_case(),
        chart_name.to_snake_case(),
        chart_name,
        hash
    )
}

/// Helper trait for case conversion.
trait CaseConvert {
    fn to_pascal_case(&self) -> String;
    fn to_snake_case(&self) -> String;
}

impl CaseConvert for str {
    fn to_pascal_case(&self) -> String {
        self.split(|c: char| c == '_' || c == '.' || c == '-' || c == ' ')
            .filter(|s| !s.is_empty())
            .map(|s| {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(f) => {
                        f.to_uppercase().to_string() + chars.as_str()
                    }
                }
            })
            .collect()
    }

    fn to_snake_case(&self) -> String {
        let mut result = String::new();
        let s = self.replace('.', "_").replace('-', "_");
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap_or(c));
        }
        result
    }
}

impl CaseConvert for String {
    fn to_pascal_case(&self) -> String {
        self.as_str().to_pascal_case()
    }
    fn to_snake_case(&self) -> String {
        self.as_str().to_snake_case()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::ScxmlDocument;

    #[test]
    fn test_case_conversion() {
        assert_eq!("hello_world".to_pascal_case(), "HelloWorld");
        assert_eq!("error.send.failed".to_pascal_case(), "ErrorSendFailed");
        assert_eq!("HelloWorld".to_snake_case(), "hello_world");
        assert_eq!("module.init".to_pascal_case(), "ModuleInit");
        assert_eq!("NivasaApplication".to_pascal_case(), "NivasaApplication");
    }

    #[test]
    fn test_codegen_produces_valid_structure() {
        let scxml = r#"<?xml version="1.0"?>
<scxml version="1.0" name="test_app" initial="idle" xmlns="http://www.w3.org/2005/07/scxml">
  <state id="idle">
    <onentry><log expr="'entering idle'"/></onentry>
    <transition event="app.start" target="running"/>
  </state>
  <state id="running">
    <onentry><log expr="'entering running'"/></onentry>
    <transition event="app.stop" target="stopped"/>
  </state>
  <final id="stopped"/>
</scxml>"#;

        let doc = ScxmlDocument::from_str(scxml).unwrap();
        let code = generate_rust(&doc);

        // Verify all expected elements are present
        assert!(code.contains("TestAppState"), "Missing state enum");
        assert!(code.contains("TestAppEvent"), "Missing event enum");
        assert!(code.contains("Idle"), "Missing Idle variant");
        assert!(code.contains("Running"), "Missing Running variant");
        assert!(code.contains("Stopped"), "Missing Stopped variant");
        assert!(code.contains("AppStart"), "Missing AppStart event");
        assert!(code.contains("AppStop"), "Missing AppStop event");
        assert!(code.contains("test_app_transition"), "Missing transition fn");
        assert!(code.contains("TestAppHandler"), "Missing handler trait");
        assert!(code.contains("on_enter_idle"), "Missing on_enter_idle handler");
        assert!(code.contains("on_enter_running"), "Missing on_enter_running handler");
        assert!(code.contains("TestAppStatechart"), "Missing spec struct");
        assert!(code.contains("sha256:"), "Missing SCXML hash");
    }

    #[test]
    fn test_codegen_transition_table() {
        let scxml = r#"<?xml version="1.0"?>
<scxml version="1.0" name="simple" initial="a" xmlns="http://www.w3.org/2005/07/scxml">
  <state id="a"><transition event="go" target="b"/></state>
  <final id="b"/>
</scxml>"#;

        let doc = ScxmlDocument::from_str(scxml).unwrap();
        let code = generate_rust(&doc);

        assert!(code.contains("(SimpleState::A, SimpleEvent::Go) => Some(SimpleState::B)"));
        assert!(code.contains("_ => None"));
    }

    #[test]
    fn test_codegen_orders_states_deterministically() {
        let scxml = r#"<?xml version="1.0"?>
<scxml version="1.0" name="order" initial="b" xmlns="http://www.w3.org/2005/07/scxml">
  <state id="b"><transition event="go" target="c"/></state>
  <state id="a"><transition event="go" target="c"/></state>
  <final id="c"/>
</scxml>"#;

        let doc = ScxmlDocument::from_str(scxml).unwrap();
        let code = generate_rust(&doc);

        let a_transition = code
            .find("(OrderState::A, OrderEvent::Go) => Some(OrderState::C)")
            .expect("missing transition for state a");
        let b_transition = code
            .find("(OrderState::B, OrderEvent::Go) => Some(OrderState::C)")
            .expect("missing transition for state b");

        assert!(a_transition < b_transition);
    }
}
