#[path = "src/codegen.rs"]
mod codegen;
#[path = "src/parser.rs"]
mod parser;
#[path = "src/schema.rs"]
mod schema;
#[path = "src/types.rs"]
mod types;
#[path = "src/validator.rs"]
mod validator;

use parser::ScxmlDocument;
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug)]
struct GeneratedChart {
    source_file: String,
    generated_file: String,
    chart_name: String,
    scxml_hash: String,
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    let statecharts_dir = statecharts_dir(&manifest_dir);
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("missing OUT_DIR"));

    println!("cargo:rerun-if-changed={}", statecharts_dir.display());

    let mut sources = collect_scxml_sources(&statecharts_dir);
    sources.sort();
    if sources.is_empty() {
        panic!(
            "no SCXML files found in {}; packaged crates must include crate-local statecharts",
            statecharts_dir.display()
        );
    }

    let mut generated = Vec::new();
    for source_path in sources {
        println!("cargo:rerun-if-changed={}", source_path.display());

        let source_name = source_path
            .file_name()
            .and_then(|name| name.to_str())
            .expect("invalid SCXML file name")
            .to_string();
        schema::validate_scxml_schema(&source_path).unwrap_or_else(|err| {
            panic!(
                "schema validation failed for {}: {}",
                source_path.display(),
                err
            )
        });

        let source = fs::read_to_string(&source_path)
            .unwrap_or_else(|err| panic!("failed to read {}: {}", source_path.display(), err));
        let document = ScxmlDocument::from_str(&source)
            .unwrap_or_else(|err| panic!("failed to parse {}: {}", source_path.display(), err));

        let validation = validator::validate(&document);
        if !validation.errors.is_empty() {
            let mut message = format!("SCXML validation failed for {}:\n", source_path.display());
            for error in validation.errors {
                let _ = writeln!(message, "  - {}", error.message);
            }
            panic!("{message}");
        }

        for warning in validation.warnings {
            println!("cargo:warning={} ({:?})", warning.message, warning.rule);
        }

        let rust_code = codegen::generate_rust_with_spec_path(&document, "crate");
        let generated_file = generated_file_name(&source_path);
        let output_path = out_dir.join(&generated_file);
        fs::write(&output_path, rust_code)
            .unwrap_or_else(|err| panic!("failed to write {}: {}", output_path.display(), err));

        generated.push(GeneratedChart {
            source_file: source_name,
            generated_file,
            chart_name: document
                .metadata
                .name
                .clone()
                .unwrap_or_else(|| "Unnamed".to_string()),
            scxml_hash: document.content_hash(),
        });
    }

    write_registry(&out_dir, &generated);
}

fn statecharts_dir(manifest_dir: &Path) -> PathBuf {
    let workspace_statecharts = manifest_dir.join("../statecharts");
    if workspace_statecharts.is_dir() {
        workspace_statecharts
    } else {
        manifest_dir.join("statecharts")
    }
}

fn collect_scxml_sources(dir: &Path) -> Vec<PathBuf> {
    let mut sources = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|ext| ext.to_str()) == Some("scxml") {
                sources.push(path);
            }
        }
    }
    sources
}

fn generated_file_name(source_path: &Path) -> String {
    let stem = source_path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("generated");
    let normalized = stem.strip_prefix("nivasa.").unwrap_or(stem);
    format!("{}_scxml.rs", normalized.replace('.', "_"))
}

fn write_registry(out_dir: &Path, generated: &[GeneratedChart]) {
    let mut mod_rs = String::from(
        "// AUTO-GENERATED by nivasa-statechart build.rs\n\
         // DO NOT EDIT - modify the .scxml file instead.\n\n",
    );

    for chart in generated {
        let _ = writeln!(mod_rs, "include!(\"{}\");", chart.generated_file);
    }

    mod_rs.push_str(
        "\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct GeneratedStatechart {\n\
             pub name: &'static str,\n\
             pub file_name: &'static str,\n\
             pub scxml_hash: &'static str,\n\
         }\n\n\
         pub const GENERATED_STATECHARTS: &[GeneratedStatechart] = &[\n",
    );

    for chart in generated {
        let _ = writeln!(
            mod_rs,
            "    GeneratedStatechart {{ name: {:?}, file_name: {:?}, scxml_hash: {:?} }},",
            chart.chart_name, chart.source_file, chart.scxml_hash
        );
    }

    mod_rs.push_str("];\n");

    let output_path = out_dir.join("mod.rs");
    fs::write(&output_path, mod_rs)
        .unwrap_or_else(|err| panic!("failed to write {}: {}", output_path.display(), err));
}
