//! Generated SCXML lifecycle for Nivasa Modules.
//!
//! This file is automatically generated by build.rs from statecharts/nivasa.module.scxml.

include!(concat!(env!("OUT_DIR"), "/module_scxml.rs"));
