use nivasa_statechart::parser::{ParseError, ScxmlDocument};
use nivasa_statechart::{HistoryType, StateType, TransitionType};
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

fn statecharts_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../statecharts")
}

fn temp_scxml_path(name: &str) -> PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    std::env::temp_dir().join(format!("nivasa-statechart-{name}-{stamp}.scxml"))
}

#[test]
fn parser_loads_checked_in_request_chart_from_file() {
    let doc = ScxmlDocument::from_file(statecharts_dir().join("nivasa.request.scxml")).unwrap();

    assert_eq!(doc.metadata.name, Some("NivasaRequest".to_string()));
    assert_eq!(doc.metadata.version, "1.0");
    assert_eq!(doc.metadata.initial, Some("received".to_string()));
    assert_eq!(doc.metadata.datamodel, Some("rust".to_string()));

    assert!(doc.has_state("received"));
    assert!(doc.has_state("error_handling"));
    assert!(doc.has_state("done"));
    assert!(doc.history_states.is_empty());

    assert_eq!(
        doc.top_level_states.first().map(String::as_str),
        Some("received")
    );
    assert_eq!(
        doc.top_level_states.last().map(String::as_str),
        Some("done")
    );

    let route_matching = &doc.states["route_matching"];
    assert_eq!(route_matching.transitions.len(), 3);
    assert!(route_matching
        .transitions
        .iter()
        .any(
            |transition| transition.event.as_deref() == Some("route.not_found")
                && transition.target == vec!["error_handling".to_string()]
        ));
}

#[test]
fn parser_captures_nested_state_features_without_changing_runtime_behavior() {
    let scxml = r#"<?xml version="1.0" encoding="UTF-8"?>
<scxml xmlns="http://www.w3.org/2005/07/scxml" version="1.0" name="coverage" initial="outer" datamodel="rust">
  <state id="outer" initial="branch_a">
    <onentry>
      <log expr="'enter outer'"/>
    </onentry>
    <onexit>
      <log expr="'exit outer'"/>
    </onexit>
    <state id="branch_a">
      <transition event="advance" cond="ready" target="branch_b branch_c" type="internal"/>
      <invoke type="service" id="svc" src="/svc" autoforward="true"/>
      <state>
        <state id="branch_leaf"/>
      </state>
    </state>
    <parallel>
      <state id="branch_b"/>
      <final id="branch_c"/>
    </parallel>
    <history id="outer_history" type="deep"/>
  </state>
</scxml>"#;

    let doc = ScxmlDocument::from_str(scxml).unwrap();

    assert_eq!(doc.metadata.name, Some("coverage".to_string()));
    assert_eq!(doc.metadata.initial, Some("outer".to_string()));
    assert_eq!(doc.metadata.datamodel, Some("rust".to_string()));

    let outer = &doc.states["outer"];
    assert_eq!(outer.state_type, StateType::Compound);
    assert!(outer.has_on_entry);
    assert!(outer.has_on_exit);
    assert_eq!(outer.children.len(), 2);
    assert_eq!(outer.children[0], "branch_a");
    assert!(outer.children[1].starts_with("__parallel_"));

    let branch_a = &doc.states["branch_a"];
    assert_eq!(branch_a.state_type, StateType::Compound);
    assert_eq!(branch_a.parent, Some("outer".to_string()));
    assert_eq!(branch_a.transitions.len(), 1);
    assert_eq!(branch_a.transitions[0].event, Some("advance".to_string()));
    assert_eq!(branch_a.transitions[0].cond, Some("ready".to_string()));
    assert_eq!(
        branch_a.transitions[0].target,
        vec!["branch_b".to_string(), "branch_c".to_string()]
    );
    assert_eq!(
        branch_a.transitions[0].transition_type,
        TransitionType::Internal
    );
    assert_eq!(branch_a.invoke.len(), 1);
    assert_eq!(branch_a.invoke[0].invoke_type, Some("service".to_string()));
    assert_eq!(branch_a.invoke[0].id, Some("svc".to_string()));
    assert_eq!(branch_a.invoke[0].src, Some("/svc".to_string()));
    assert!(branch_a.invoke[0].autoforward);

    let anonymous_id = doc
        .states
        .keys()
        .find(|id| id.starts_with("__anonymous_"))
        .cloned()
        .expect("expected autogenerated anonymous state id");
    let anonymous = &doc.states[&anonymous_id];
    assert_eq!(anonymous.state_type, StateType::Compound);
    assert_eq!(anonymous.parent, Some("branch_a".to_string()));
    assert_eq!(anonymous.children, vec!["branch_leaf".to_string()]);

    let parallel_id = outer.children[1].clone();
    let parallel = &doc.states[&parallel_id];
    assert_eq!(parallel.state_type, StateType::Parallel);
    assert_eq!(parallel.parent, Some("outer".to_string()));
    assert_eq!(
        parallel.children,
        vec!["branch_b".to_string(), "branch_c".to_string()]
    );

    assert_eq!(doc.history_states.len(), 1);
    assert_eq!(doc.history_states[0].id, "outer_history");
    assert_eq!(doc.history_states[0].history_type, HistoryType::Deep);
    assert_eq!(doc.history_states[0].parent, "outer");
}

#[test]
fn parser_reports_missing_root_element() {
    let path = temp_scxml_path("missing-root");
    fs::write(&path, r#"<state id="idle"/>"#).unwrap();

    let result = ScxmlDocument::from_file(&path);
    fs::remove_file(&path).ok();

    match result {
        Err(ParseError::Invalid(message)) => {
            assert!(
                message.contains("Missing <scxml> root element"),
                "unexpected parser error: {message}"
            );
        }
        other => panic!("expected missing-root parse error, got {other:?}"),
    }
}
