//! Generated SCXML lifecycle for DI Providers.
//!
//! This file is automatically generated by build.rs from statecharts/nivasa.provider.scxml.

include!(concat!(env!("OUT_DIR"), "/provider_scxml.rs"));
