use crate::di::error::DiError;
use async_trait::async_trait;
use std::any::{Any, TypeId};
use std::sync::Arc;
use tokio::sync::Mutex;

use crate::di::lifecycle::{NivasaProviderEvent, NivasaProviderState, NivasaProviderStatechart};
use nivasa_statechart::StatechartEngine;

/// Lifespan scope of a provider instance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum ProviderScope {
    /// A single instance is created and shared across the entire application lifecycle.
    #[default]
    Singleton,
    /// A new instance is created for every incoming request.
    Scoped,
    /// A new instance is created every time it is injected or resolved.
    Transient,
}

/// Metadata describing a registered provider.
#[derive(Debug, Clone)]
pub struct ProviderMetadata {
    /// The unique TypeId of the type this provider resolves.
    pub type_id: TypeId,
    /// The human-readable name of the type (for debugging/errors).
    pub type_name: &'static str,
    /// The scope of this provider.
    pub scope: ProviderScope,
    /// The TypeIds of the dependencies this provider requires to be built.
    pub dependencies: Vec<TypeId>,
}

/// The core interface for anything that can provide a dependency.
#[async_trait]
pub trait Provider: Send + Sync + 'static {
    /// Get the metadata for this provider.
    fn metadata(&self) -> &ProviderMetadata;

    /// Build the instance. Depending on the `ProviderScope`, the DI container
    /// may cache this result (e.g. for Singletons) or call this repeatedly.
    async fn build(
        &self,
        container: &crate::di::container::DependencyContainer,
    ) -> Result<Arc<dyn Any + Send + Sync>, DiError>;
}

/// Trait implemented by types that can be injected via the DI container.
/// Usually generated by the `#[injectable]` macro.
#[async_trait]
pub trait Injectable: Sized + Send + Sync + 'static {
    /// Build the injectable instance from the container.
    async fn build(container: &crate::di::container::DependencyContainer) -> Result<Self, DiError>;

    /// Return the dependencies required to build this injectable.
    fn dependencies() -> Vec<TypeId>;
}

/// A provider that wraps another provider and enforces an SCXML lifecycle.
pub struct LifecycleProvider {
    inner: Arc<dyn Provider>,
    engine: Mutex<StatechartEngine<NivasaProviderStatechart>>,
}

impl LifecycleProvider {
    /// Wrap an existing provider with lifecycle tracking.
    pub fn new(inner: Arc<dyn Provider>) -> Self {
        let mut engine = StatechartEngine::new(NivasaProviderState::Unregistered);
        // Move from Unregistered to Registered immediately upon wrapping for the container
        let _ = engine.send_event(NivasaProviderEvent::ProviderRegister);

        Self {
            inner,
            engine: Mutex::new(engine),
        }
    }

    /// Return the current lifecycle state.
    pub async fn state(&self) -> NivasaProviderState {
        self.engine.lock().await.current_state()
    }
}

#[async_trait]
impl Provider for LifecycleProvider {
    fn metadata(&self) -> &ProviderMetadata {
        self.inner.metadata()
    }

    async fn build(
        &self,
        container: &crate::di::container::DependencyContainer,
    ) -> Result<Arc<dyn Any + Send + Sync>, DiError> {
        let mut engine = self.engine.lock().await;

        // 1. Start resolution
        engine
            .send_event(NivasaProviderEvent::ProviderResolve)
            .map_err(|e| DiError::Registration(format!("Invalid state transition: {}", e)))?;

        // 2. Dependencies Ready
        engine
            .send_event(NivasaProviderEvent::DependenciesReady)
            .map_err(|e| DiError::Registration(format!("Invalid state transition: {}", e)))?;

        // 3. Constructing
        // Perform the actual build
        let result = self.inner.build(container).await;

        match result {
            Ok(instance) => {
                let _ = engine.send_event(NivasaProviderEvent::ProviderConstructed);
                Ok(instance)
            }
            Err(e) => {
                let _ = engine.send_event(NivasaProviderEvent::ErrorConstruction);
                Err(e)
            }
        }
    }
}

/// A provider that wraps a pre-constructed value.
pub struct ValueProvider<T: Send + Sync + 'static> {
    metadata: ProviderMetadata,
    value: Arc<T>,
}

impl<T: Send + Sync + 'static> ValueProvider<T> {
    /// Create a singleton provider from an owned value.
    pub fn new(value: T) -> Self {
        Self::new_from_arc(Arc::new(value))
    }

    /// Create a singleton provider from a shared value.
    pub fn new_from_arc(value: Arc<T>) -> Self {
        Self {
            metadata: ProviderMetadata {
                type_id: TypeId::of::<T>(),
                type_name: std::any::type_name::<T>(),
                scope: ProviderScope::Singleton,
                dependencies: vec![],
            },
            value,
        }
    }
}

#[async_trait]
impl<T: Send + Sync + 'static> Provider for ValueProvider<T> {
    fn metadata(&self) -> &ProviderMetadata {
        &self.metadata
    }

    async fn build(
        &self,
        _container: &crate::di::container::DependencyContainer,
    ) -> Result<Arc<dyn Any + Send + Sync>, DiError> {
        Ok(self.value.clone())
    }
}

/// A provider that uses a factory function to construct the value.
pub struct FactoryProvider<T, F>
where
    T: Send + Sync + 'static,
    F: for<'a> Fn(
            &'a crate::di::container::DependencyContainer,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<T, DiError>> + Send + 'a>,
        > + Send
        + Sync
        + 'static,
{
    metadata: ProviderMetadata,
    factory: F,
}

impl<T, F> FactoryProvider<T, F>
where
    T: Send + Sync + 'static,
    F: for<'a> Fn(
            &'a crate::di::container::DependencyContainer,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<T, DiError>> + Send + 'a>,
        > + Send
        + Sync
        + 'static,
{
    /// Create a provider backed by an async factory.
    pub fn new(scope: ProviderScope, dependencies: Vec<TypeId>, factory: F) -> Self {
        Self {
            metadata: ProviderMetadata {
                type_id: TypeId::of::<T>(),
                type_name: std::any::type_name::<T>(),
                scope,
                dependencies,
            },
            factory,
        }
    }
}

#[async_trait]
impl<T, F> Provider for FactoryProvider<T, F>
where
    T: Send + Sync + 'static,
    F: for<'a> Fn(
            &'a crate::di::container::DependencyContainer,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<T, DiError>> + Send + 'a>,
        > + Send
        + Sync
        + 'static,
{
    fn metadata(&self) -> &ProviderMetadata {
        &self.metadata
    }

    async fn build(
        &self,
        container: &crate::di::container::DependencyContainer,
    ) -> Result<Arc<dyn Any + Send + Sync>, DiError> {
        let instance = (self.factory)(container).await?;
        Ok(Arc::new(instance))
    }
}

/// A provider that constructs a class (struct) by calling its `Injectable::build` method.
pub struct ClassProvider<T, F>
where
    T: Send + Sync + 'static,
    F: for<'a> Fn(
            &'a crate::di::container::DependencyContainer,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<T, DiError>> + Send + 'a>,
        > + Send
        + Sync
        + 'static,
{
    metadata: ProviderMetadata,
    constructor: F,
}

impl<T, F> ClassProvider<T, F>
where
    T: Send + Sync + 'static,
    F: for<'a> Fn(
            &'a crate::di::container::DependencyContainer,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<T, DiError>> + Send + 'a>,
        > + Send
        + Sync
        + 'static,
{
    /// Create a provider backed by an async constructor.
    pub fn new(scope: ProviderScope, dependencies: Vec<TypeId>, constructor: F) -> Self {
        Self {
            metadata: ProviderMetadata {
                type_id: TypeId::of::<T>(),
                type_name: std::any::type_name::<T>(),
                scope,
                dependencies,
            },
            constructor,
        }
    }
}

#[async_trait]
impl<T, F> Provider for ClassProvider<T, F>
where
    T: Send + Sync + 'static,
    F: for<'a> Fn(
            &'a crate::di::container::DependencyContainer,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<T, DiError>> + Send + 'a>,
        > + Send
        + Sync
        + 'static,
{
    fn metadata(&self) -> &ProviderMetadata {
        &self.metadata
    }

    async fn build(
        &self,
        container: &crate::di::container::DependencyContainer,
    ) -> Result<Arc<dyn Any + Send + Sync>, DiError> {
        let instance = (self.constructor)(container).await?;
        Ok(Arc::new(instance))
    }
}
